#webdriver.driver=chrome
#webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
webdriver.driver=firefox
webdriver.gecko.driver=src/test/resources/drivers/geckodriver.exe
serenity.project.name=Product Store
webdriver.base.url=https://www.demoblaze.com/
webdriver.timeouts.implicitlywait=30000
webdriver.wait.for.timeout=
report.tagtypes=capability,feature
serenity.dry.run=FALSE
serenity.release.types=Version,Iteration
serenity.take.screenshots=AFTER_EACH_STEP
serenity.logging=VERBOSE
serenity.verbose.com.mail.steps=true
serenity.verbose.steps=true
serenity.console.colors=true
serenity.reports.show.step.details=true
serenity.timeout=9000
serenity.report.encoding=UTF-8
feature.file.encoding=UTF-8
story.timeout.in.secs=5000
chrome.switches=--disk-cache-dir=null, --disable-popup-blocking, --incognito, --disable-download-notification,--start-maximized,--test-type,--ignore-certificate-errors, --allow-running-insecure-content, --disable-translate, --always-authorize-plugins, --disable-extensions